spring.datasource.url=jdbc:mysql://localhost:3306/tarea2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=vivadbz23V
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# Optional dialect (Hibernate can usually auto-detect)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
